version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: printerlogic/pl-summit-2019:${DOCKER_TAG_APP:-latest-edge}
    volumes:
      - ./:/var/www/app:consistent
    env_file:
      - .env.local
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - mysql
    networks:
      - overlay
    healthcheck:
      test: curl -fk https://localhost
      interval: 60s
      timeout: 10s
      retries: 30
      start_period: 10s

  mysql:
    image: mysql:5.6
    volumes:
    - "${DOCKER_VOLUME_MYSQL_STORAGE:-./.docker-storage/db/}:/var/lib/mysql"
    ports:
    - "${DOCKER_PORT_MYSQL:-13306}:3306"
    networks:
    - overlay
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-pl_summit}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
    healthcheck:
      test: mysqladmin -u${DB_USERNAME:-root} -p${DB_PASSWORD:-password} ping
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  overlay: