version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    # We use the latest-edge tag for the service under development; all other services should use the "latest" tag
    image: printerlogic/pl-summit-2019:${DOCKER_TAG_APP:-latest-edge}
    volumes:
      - ./:/var/www/app:consistent
    env_file:
      - .env.local
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - overlay

  mysql:
    image: mysql:5.6
    volumes:
    - "${DOCKER_VOLUME_MYSQL_STORAGE:-./.docker-storage/db/}:/var/lib/mysql"
    ports:
    - "${DOCKER_PORT_MYSQL:-13306}:3306"
    networks:
    - overlay
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-pl_summit}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"

networks:
  overlay: